# Generated by Django 2.0.3 on 2018-03-13 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_first', to='currencies.Currency')),
                ('currency_second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_second', to='currencies.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Pair')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('currency_first', 'currency_second')},
        ),
    ]
